name = "EarthBox"
uuid = "8cac4eb0-b9dc-491e-8029-d46e41f70254"
authors = ["Erik Kneller"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
MUMPS = "55d2b088-9f4e-11e9-26c0-150b02ea6a46"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.11, 1.12"
CairoMakie = "0.14.0"
Plots = "1.40.11"
MPI = "0.20.22"
MPIPreferences = "0.1.11"
MUMPS = "1.5.1"
DataStructures = "0.18"
FilePathsBase = "0.9.24"
JLD2 = "0.5.12"
TOML = "1.0.3"
YAML = "0.4.9"
SpecialFunctions = "2.3.1"
StaticArrays = "1.9"



