[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
EarthBox = "8cac4eb0-b9dc-491e-8029-d46e41f70254"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[extras]
EarthBox = "8cac4eb0-b9dc-491e-8029-d46e41f70254"

[targets]
test = ["EarthBox"]
